# Generated by Django 5.2.7 on 2025-11-30 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Viewer's full name", max_length=200)),
                ('email', models.EmailField(help_text="Viewer's email address", max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text="Viewer's phone number (optional)", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this viewer profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup_user', models.ForeignKey(help_text='The user who set up the detection system', on_delete=django.db.models.deletion.CASCADE, related_name='viewer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viewer Profile',
                'verbose_name_plural': 'Viewer Profiles',
                'unique_together': {('setup_user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FallAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the fall was detected')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Fall'), ('false_alarm', 'False Alarm')], default='pending', help_text='Current status of the alert', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score of the detection', null=True)),
                ('consecutive_frames', models.IntegerField(default=0, help_text='Number of consecutive frames with fall detection')),
                ('snapshot_path', models.CharField(blank=True, help_text='Path to the saved snapshot image', max_length=500)),
                ('detection_info', models.TextField(blank=True, help_text='Additional detection information (JSON format)')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the alert was confirmed/rejected', null=True)),
                ('whatsapp_sent', models.BooleanField(default=False, help_text='Whether WhatsApp notification was sent')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='User who confirmed/rejected this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_alerts', to=settings.AUTH_USER_MODEL)),
                ('setup_user', models.ForeignKey(help_text='The user who set up the detection system', on_delete=django.db.models.deletion.CASCADE, related_name='fall_alerts', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, help_text='Viewer assigned to review this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dashboard.viewerprofile')),
            ],
            options={
                'verbose_name': 'Fall Alert',
                'verbose_name_plural': 'Fall Alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
