# Generated by Django 5.2.7 on 2025-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_viewerprofile_fallalert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewerprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='viewerprofile',
            name='setup_user',
        ),
        migrations.DeleteModel(
            name='FallAlert',
        ),
        migrations.DeleteModel(
            name='ViewerProfile',
        ),
    ]
