# Generated by Django 5.2.4 on 2025-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
